export const PLANS = [
  {
    id: "free",
    name: "Free",
    price: 0,
    currency: "USD",
    tagline: "Explore the platform",
    icon: "🆓",
    features: [
      "Create healthcare profile",
      "Upload CV",
      "Basic job search",
      "Up to 3 AI recommendations",
      "Limited job alerts",
      "Save jobs",
      "View basic job details",
    ],
  },
  {
    id: "basic",
    name: "Basic",
    price: 2,
    currency: "USD",
    tagline: "Essential job alerts",
    icon: "🌱",
    features: [
      "Everything in Free",
      "AI CV analysis",
      "Basic job matching",
      "Up to 10 personalized recommendations",
      "Job alerts & email notifications",
      "Basic application tracking",
      "Country & remote preferences",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    price: 5,
    currency: "USD",
    tagline: "For active job seekers",
    icon: "🚀",
    popular: true,
    features: [
      "Everything in Basic",
      "Advanced AI job matching",
      "Unlimited recommendations",
      "International job recommendations",
      "AI CV optimization & cover letters",
      "Application preparation",
      "Visa & registration indicators",
      "Salary information",
      "Interview preparation",
      "Multiple search profiles",
      "Priority job alerts",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: 10,
    currency: "USD",
    tagline: "For international careers",
    icon: "👑",
    features: [
      "Everything in Professional",
      "Priority AI matching & early alerts",
      "Global opportunity monitoring",
      "AI career advisor",
      "Multiple CV versions & international formats",
      "Career gap analysis & skill recommendations",
      "Employer intelligence",
      "Visa sponsorship detection",
      "NGO & humanitarian alerts",
      "Emergency/pandemic alerts",
      "Personalized career strategy",
    ],
  },
];

export const PLAN_FEATURES = {
  free: {
    aiCvAnalysis: false,
    aiCvOptimization: false,
    coverLetters: false,
    applicationPrep: false,
    interviewPrep: false,
    careerAdvisor: false,
    multipleSearchProfiles: false,
    internationalRecommendations: false,
    priorityAlerts: false,
    ngoAlerts: false,
    emergencyAlerts: false,
    multipleCvVersions: false,
    employerIntelligence: false,
    careerGapAnalysis: false,
    salaryInfo: false,
    visaIndicators: false,
    registrationDetection: false,
    recommendationsLimit: 3,
    alertsLimit: 3,
  },
  basic: {
    aiCvAnalysis: true,
    aiCvOptimization: false,
    coverLetters: false,
    applicationPrep: false,
    interviewPrep: false,
    careerAdvisor: false,
    multipleSearchProfiles: false,
    internationalRecommendations: false,
    priorityAlerts: false,
    ngoAlerts: false,
    emergencyAlerts: false,
    multipleCvVersions: false,
    employerIntelligence: false,
    careerGapAnalysis: false,
    salaryInfo: false,
    visaIndicators: false,
    registrationDetection: false,
    recommendationsLimit: 10,
    alertsLimit: 10,
  },
  professional: {
    aiCvAnalysis: true,
    aiCvOptimization: true,
    coverLetters: true,
    applicationPrep: true,
    interviewPrep: true,
    careerAdvisor: false,
    multipleSearchProfiles: true,
    internationalRecommendations: true,
    priorityAlerts: true,
    ngoAlerts: false,
    emergencyAlerts: false,
    multipleCvVersions: false,
    employerIntelligence: false,
    careerGapAnalysis: false,
    salaryInfo: true,
    visaIndicators: true,
    registrationDetection: true,
    recommendationsLimit: Infinity,
    alertsLimit: 50,
  },
  premium: {
    aiCvAnalysis: true,
    aiCvOptimization: true,
    coverLetters: true,
    applicationPrep: true,
    interviewPrep: true,
    careerAdvisor: true,
    multipleSearchProfiles: true,
    internationalRecommendations: true,
    priorityAlerts: true,
    ngoAlerts: true,
    emergencyAlerts: true,
    multipleCvVersions: true,
    employerIntelligence: true,
    careerGapAnalysis: true,
    salaryInfo: true,
    visaIndicators: true,
    registrationDetection: true,
    recommendationsLimit: Infinity,
    alertsLimit: Infinity,
  },
};

export const getPlan = (id) => PLANS.find((p) => p.id === id) || PLANS[0];

export const formatLimit = (n) => (n === Infinity ? "Unlimited" : String(n));